# Generated by Django 5.2.9 on 2025-12-20 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(default="Home", max_length=100)),
                ("address_line1", models.CharField(max_length=255)),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("country", models.CharField(default="India", max_length=100)),
                ("is_default_shipping", models.BooleanField(default=False)),
                ("is_default_billing", models.BooleanField(default=False)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        db_constraint=False,
                        to="accounts.contact",
                    ),
                ),
            ],
            options={
                "db_table": "addresses",
                "indexes": [
                    models.Index(fields=["contact"], name="idx_address_contact"),
                    models.Index(
                        fields=["is_default_shipping"], name="idx_address_ship"
                    ),
                    models.Index(
                        fields=["is_default_billing"], name="idx_address_bill"
                    ),
                ],
            },
        ),
    ]
