# Generated by Django 5.2.9 on 2025-12-20 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purchase_order_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("po_number", models.CharField(max_length=50, unique=True)),
                ("order_date", models.DateField()),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "po_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="accounts.contact",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_orders",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("po_line_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("line_number", models.IntegerField()),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=15)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "line_subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "line_tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "received_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_lines",
                        to="catalog.product",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchases.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order_lines",
            },
        ),
        migrations.CreateModel(
            name="VendorBill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor_bill_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("bill_number", models.CharField(max_length=50, unique=True)),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "bill_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vendor_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_bills_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_bills",
                        to="purchases.purchaseorder",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_bills",
                        to="accounts.contact",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_bills",
            },
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["po_number"], name="idx_po_number"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["vendor"], name="idx_po_vendor"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["po_status"], name="idx_po_status"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["order_date"], name="idx_po_order_date"),
        ),
        migrations.AddIndex(
            model_name="purchaseorderline",
            index=models.Index(fields=["purchase_order"], name="idx_po_line_po"),
        ),
        migrations.AddIndex(
            model_name="purchaseorderline",
            index=models.Index(fields=["product"], name="idx_po_line_product"),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseorderline",
            unique_together={("purchase_order", "line_number")},
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(fields=["bill_number"], name="idx_bill_number"),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(fields=["vendor"], name="idx_bill_vendor"),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(fields=["purchase_order"], name="idx_bill_po"),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(fields=["bill_status"], name="idx_bill_status"),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(
                fields=["invoice_date", "due_date"], name="idx_bill_dates"
            ),
        ),
    ]
