# Generated by Django 5.2.9 on 2025-12-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="confirmed_by",
            field=models.BigIntegerField(
                blank=True, db_column="confirmed_by", null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="created_by",
            field=models.BigIntegerField(blank=True, db_column="created_by", null=True),
        ),
        migrations.AlterField(
            model_name="vendorbill",
            name="created_by",
            field=models.BigIntegerField(blank=True, db_column="created_by", null=True),
        ),
    ]
