# Generated by Django 5.2.9 on 2026-01-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0002_alter_purchaseorder_confirmed_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorderline",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="purchaseorderline",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="vendorbill",
            name="remaining_amount",
            field=models.DecimalField(
                blank=True,
                db_default=None,
                decimal_places=2,
                editable=False,
                max_digits=15,
                null=True,
            ),
        ),
    ]
