# Generated by Django 5.2.9 on 2025-12-20 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=255)),
                ("product_code", models.CharField(max_length=50, unique=True)),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("men", "Men"),
                            ("women", "Women"),
                            ("children", "Children"),
                            ("unisex", "Unisex"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("shirt", "Shirt"),
                            ("pant", "Pant"),
                            ("kurta", "Kurta"),
                            ("t-shirt", "T-shirt"),
                            ("jeans", "Jeans"),
                            ("dress", "Dress"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("material", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "current_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "minimum_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                ("sales_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "sales_tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "purchase_tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("color_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("color_name", models.CharField(max_length=50)),
                ("color_code", models.CharField(blank=True, max_length=7, null=True)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colors",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_colors",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("image_url", models.URLField(max_length=500)),
                (
                    "image_alt_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_images",
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["product_code"], name="idx_product_code"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_category"], name="idx_product_category"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["product_type"], name="idx_product_type"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_published"], name="idx_product_published"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_active"], name="idx_product_active"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["current_stock"], name="idx_product_stock"),
        ),
        migrations.AddIndex(
            model_name="productcolor",
            index=models.Index(fields=["product"], name="idx_color_product"),
        ),
        migrations.AlterUniqueTogether(
            name="productcolor",
            unique_together={("product", "color_name")},
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(fields=["product"], name="idx_image_product"),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(fields=["is_primary"], name="idx_image_primary"),
        ),
    ]
