# Generated by Django 5.2.9 on 2025-12-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_by",
            field=models.BigIntegerField(blank=True, db_column="created_by", null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_by",
            field=models.BigIntegerField(blank=True, db_column="updated_by", null=True),
        ),
    ]
