# Generated by Django 5.2.9 on 2025-12-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_created_by_alter_product_updated_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcolor",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="productcolor",
            name="updated_at",
        ),
    ]
