# Generated by Django 5.2.9 on 2026-01-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_productcolor_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="updated_at",
        ),
    ]
