# Generated by Django 5.2.9 on 2025-12-20 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountOffer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_offer_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("offer_name", models.CharField(max_length=255)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "available_on",
                    models.CharField(
                        choices=[
                            ("sales", "Sales"),
                            ("website", "Website"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discounts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "discount_offers",
            },
        ),
        migrations.CreateModel(
            name="CouponCode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("coupon_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("coupon_code", models.CharField(max_length=50, unique=True)),
                ("expiration_date", models.DateField()),
                (
                    "coupon_status",
                    models.CharField(
                        choices=[
                            ("unused", "Unused"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                        ],
                        default="unused",
                        max_length=10,
                    ),
                ),
                ("usage_count", models.IntegerField(default=0)),
                ("max_usage_count", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupons",
                        to="accounts.contact",
                    ),
                ),
                (
                    "discount_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="pricing.discountoffer",
                    ),
                ),
            ],
            options={
                "db_table": "coupon_codes",
            },
        ),
        migrations.CreateModel(
            name="PaymentTerm",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_term_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("term_name", models.CharField(max_length=100, unique=True)),
                ("net_days", models.IntegerField(default=0)),
                ("early_payment_discount", models.BooleanField(default=False)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("discount_days", models.IntegerField(default=0)),
                (
                    "early_pay_discount_computation",
                    models.CharField(
                        choices=[
                            ("base_amount", "Base Amount"),
                            ("total_amount", "Total Amount"),
                        ],
                        default="base_amount",
                        max_length=20,
                    ),
                ),
                ("example_preview", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "payment_terms",
                "indexes": [
                    models.Index(fields=["term_name"], name="idx_term_name"),
                    models.Index(fields=["is_active"], name="idx_term_active"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="discountoffer",
            index=models.Index(
                fields=["start_date", "end_date"], name="idx_offer_dates"
            ),
        ),
        migrations.AddIndex(
            model_name="discountoffer",
            index=models.Index(fields=["available_on"], name="idx_offer_available"),
        ),
        migrations.AddIndex(
            model_name="discountoffer",
            index=models.Index(fields=["is_active"], name="idx_offer_active"),
        ),
        migrations.AddIndex(
            model_name="couponcode",
            index=models.Index(fields=["coupon_code"], name="idx_coupon_code"),
        ),
        migrations.AddIndex(
            model_name="couponcode",
            index=models.Index(fields=["coupon_status"], name="idx_coupon_status"),
        ),
        migrations.AddIndex(
            model_name="couponcode",
            index=models.Index(fields=["contact"], name="idx_coupon_contact"),
        ),
        migrations.AddIndex(
            model_name="couponcode",
            index=models.Index(
                fields=["expiration_date"], name="idx_coupon_expiration"
            ),
        ),
    ]
