# Generated by Django 5.2.9 on 2025-12-20 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("audit_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("table_name", models.CharField(max_length=100)),
                ("record_id", models.BigIntegerField()),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("INSERT", "INSERT"),
                            ("UPDATE", "UPDATE"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=10,
                    ),
                ),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("changed_by", models.BigIntegerField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "audit_log",
                "indexes": [
                    models.Index(
                        fields=["table_name", "record_id"],
                        name="idx_audit_table_record",
                    ),
                    models.Index(fields=["created_at"], name="idx_audit_changed_at"),
                    models.Index(fields=["changed_by"], name="idx_audit_changed_by"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("document_type", models.CharField(max_length=50, unique=True)),
                ("prefix", models.CharField(max_length=20)),
                ("next_number", models.BigIntegerField(default=1)),
                ("padding", models.IntegerField(default=6)),
            ],
            options={
                "db_table": "document_sequences",
                "indexes": [
                    models.Index(fields=["document_type"], name="idx_doc_type")
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("setting_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("setting_key", models.CharField(max_length=100, unique=True)),
                ("setting_value", models.TextField(blank=True, null=True)),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settings_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_settings",
                "indexes": [
                    models.Index(fields=["setting_key"], name="idx_setting_key")
                ],
            },
        ),
    ]
