# Generated by Django 5.2.9 on 2025-12-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlog",
            name="idx_audit_changed_at",
        ),
        migrations.RenameField(
            model_name="auditlog",
            old_name="created_at",
            new_name="changed_at",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="documentsequence",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="systemsetting",
            name="created_at",
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["changed_at"], name="idx_audit_changed_at"),
        ),
    ]
