# Generated by Django 5.2.9 on 2025-12-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_remove_auditlog_idx_audit_changed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsetting",
            name="updated_by",
            field=models.BigIntegerField(blank=True, db_column="updated_by", null=True),
        ),
    ]
