# Generated by Django 5.2.9 on 2025-12-20 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("movement_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("sale", "Sale"),
                            ("adjustment", "Adjustment"),
                            ("return", "Return"),
                        ],
                        max_length=20,
                    ),
                ),
                ("movement_date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=15)),
                (
                    "movement_direction",
                    models.CharField(
                        choices=[("in", "In"), ("out", "Out")], max_length=3
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("purchase_order", "Purchase Order"),
                            ("sales_order", "Sales Order"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference_id", models.BigIntegerField()),
                ("stock_before", models.DecimalField(decimal_places=3, max_digits=15)),
                ("stock_after", models.DecimalField(decimal_places=3, max_digits=15)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "stock_movements",
                "indexes": [
                    models.Index(fields=["product"], name="idx_movement_product"),
                    models.Index(fields=["movement_date"], name="idx_movement_date"),
                    models.Index(fields=["movement_type"], name="idx_movement_type"),
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="idx_movement_reference",
                    ),
                ],
            },
        ),
    ]
