# Generated by Django 5.2.9 on 2025-12-20 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
        ("pricing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sales_order_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("so_number", models.CharField(max_length=50, unique=True)),
                ("order_date", models.DateField()),
                (
                    "order_source",
                    models.CharField(
                        choices=[("backend", "Backend"), ("website", "Website")],
                        default="backend",
                        max_length=10,
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("invoiced", "Invoiced"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "applied_discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "shipping_address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_pincode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_orders",
                        to="pricing.couponcode",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="accounts.contact",
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="pricing.paymentterm",
                    ),
                ),
            ],
            options={
                "db_table": "sales_orders",
            },
        ),
        migrations.CreateModel(
            name="CustomerInvoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_invoice_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "invoice_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "early_payment_discount_applicable",
                    models.BooleanField(default=False),
                ),
                (
                    "early_payment_discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("early_payment_deadline", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="accounts.contact",
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="pricing.paymentterm",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "db_table": "customer_invoices",
            },
        ),
        migrations.CreateModel(
            name="SalesOrderLine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("so_line_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("line_number", models.IntegerField()),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=15)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "line_subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "line_tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "invoiced_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_lines",
                        to="catalog.product",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "db_table": "sales_order_lines",
            },
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["so_number"], name="idx_so_number"),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["customer"], name="idx_so_customer"),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["order_status"], name="idx_so_status"),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["order_source"], name="idx_so_source"),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["order_date"], name="idx_so_order_date"),
        ),
        migrations.AddIndex(
            model_name="customerinvoice",
            index=models.Index(fields=["invoice_number"], name="idx_invoice_number"),
        ),
        migrations.AddIndex(
            model_name="customerinvoice",
            index=models.Index(fields=["customer"], name="idx_invoice_customer"),
        ),
        migrations.AddIndex(
            model_name="customerinvoice",
            index=models.Index(fields=["sales_order"], name="idx_invoice_sales_order"),
        ),
        migrations.AddIndex(
            model_name="customerinvoice",
            index=models.Index(fields=["invoice_status"], name="idx_invoice_status"),
        ),
        migrations.AddIndex(
            model_name="customerinvoice",
            index=models.Index(
                fields=["invoice_date", "due_date"], name="idx_invoice_dates"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorderline",
            index=models.Index(fields=["sales_order"], name="idx_sales_order"),
        ),
        migrations.AddIndex(
            model_name="salesorderline",
            index=models.Index(fields=["product"], name="idx_sales_product"),
        ),
        migrations.AlterUniqueTogether(
            name="salesorderline",
            unique_together={("sales_order", "line_number")},
        ),
    ]
