# Generated by Django 5.2.9 on 2025-12-20 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_address"),
        ("pricing", "0002_alter_discountoffer_created_by"),
        ("sales", "0002_alter_customerinvoice_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrderStatusLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("previous_status", models.CharField(max_length=15)),
                ("new_status", models.CharField(max_length=15)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "sales_order_status_logs",
            },
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_orders",
                to="accounts.address",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_country",
            field=models.CharField(default="India", max_length=100),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("confirmed", "Confirmed"),
                    ("invoiced", "Invoiced"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["shipping_address"], name="idx_so_ship_address"),
        ),
        migrations.AddField(
            model_name="salesorderstatuslog",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_status_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesorderstatuslog",
            name="sales_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="sales.salesorder",
            ),
        ),
        migrations.AddIndex(
            model_name="salesorderstatuslog",
            index=models.Index(fields=["sales_order"], name="idx_so_statuslog_order"),
        ),
        migrations.AddIndex(
            model_name="salesorderstatuslog",
            index=models.Index(fields=["new_status"], name="idx_so_statuslog_status"),
        ),
    ]
