# Generated by Django 5.2.9 on 2025-12-20 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_productcolor_created_at_and_more"),
        ("sales", "0003_salesorderstatuslog_salesorder_shipping_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cart_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        db_constraint=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "carts",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart_item_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=15)),
                (
                    "selected_size",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "selected_color",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cart_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "cart_items",
            },
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["user"], name="idx_cart_user"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["cart"], name="idx_cartitem_cart"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["product"], name="idx_cartitem_product"),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product", "selected_size", "selected_color")},
        ),
    ]
