# Generated by Django 5.2.9 on 2026-01-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_cart_cartitem_cart_idx_cart_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesorderline",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="salesorderline",
            name="updated_at",
        ),
    ]
