# Generated by Django 5.2.9 on 2025-12-20 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("purchases", "0001_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payment_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("payment_number", models.CharField(max_length=50, unique=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("customer_payment", "Customer Payment"),
                            ("vendor_payment", "Vendor Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("upi", "UPI"),
                            ("wallet", "Wallet"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="completed",
                        max_length=10,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="accounts.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments",
            },
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("allocation_date", models.DateField()),
                ("early_payment_discount_applied", models.BooleanField(default=False)),
                (
                    "discount_amount_applied",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "customer_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="sales.customerinvoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="payments.payment",
                    ),
                ),
                (
                    "vendor_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="purchases.vendorbill",
                    ),
                ),
            ],
            options={
                "db_table": "payment_allocations",
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["payment_number"], name="idx_payment_number"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["contact"], name="idx_payment_contact"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["payment_type"], name="idx_payment_type"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["payment_date"], name="idx_payment_date"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["payment_status"], name="idx_payment_status"),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(fields=["payment"], name="idx_payalloc_payment"),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["customer_invoice"], name="idx_payalloc_invoice"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(fields=["vendor_bill"], name="idx_payalloc_bill"),
        ),
    ]
