# Generated by Django 5.2.9 on 2026-01-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentallocation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="paymentallocation",
            name="updated_at",
        ),
    ]
